# configs/ubuntu22.04.yaml
system_packages:
  - curl
  - git

github_repos:
  - name: PX4-Autopilot
    url: https://github.com/Temasek-Dynamics/PX4-Autopilot.git
    branch: v1.13.0_raynor
    path: submodules/PX4-Autopilot

python_packages:
  - torch
  - numpy
