# configs/ubuntu22.04.yaml
system_packages:
  - yp
  - curl
  - git

github_repos:
  - name: pegasus
    url: "https://github.com/Temasek-Dynamics/PegasusSimulator.git"
    branch: main
    path: "submodules/PegasusSimulator"

python_packages:
  - torch
  - numpy
