# configs/ubuntu22.04.yaml
system_packages:
  - curl
  - git
  - tmux

github_repos:
  - name: pegasus
    url: "https://github.com/CarlsonGYC/PegasusSimulator.git"
    branch: dev_yichao
    path: "submodules/PegasusSimulator"
  - name: PX4-Autopilot
    url: https://github.com/CarlsonGYC/PX4-Autopilot.git
    branch: dev_yichao
    path: submodules/PX4-Autopilot

python_packages:
  - torch
  - numpy
